#!/bin/bash

if [ -z "$1" ]
then
    echo "usage) docker-deploy site.com jae@docker-server.com"
    exit 1
fi
if [ -z "$2" ]
then
    echo "usage) docker-deploy site.com jae@docker-server.com"
    exit 1
fi

project=$1
target=$2
host=$(echo $target | cut -f2 -d@)

# if docker doesnt exist on server, install it
docker_exist=`ssh $2 which docker`
if [[ -z "$docker_exist" ]]
then
    echo "docker not exist, installing docker, one moment ..."
    #docker-machine create -d "generic" --generic-ip-address="$host" --generic-ssh-user="root" $1
    ssh $2 'curl -sSL https://get.docker.com/ | sh'
fi

# if docker-compose doesnt exist on server, install it
docker_compose_exist=`ssh $2 which docker-compose`
if [[ -z "$docker_compose_exist" ]]
then
    echo "docker-compose not exist, installing docker-compose, one moment ..."
    ssh $2 'curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose'
    ssh $2 "chmod +x /usr/local/bin/docker-compose"
fi

# if docker container nginx-proxy is not running, run it
docker_proxy_exist=`ssh $2 docker ps |grep jwilder/nginx-proxy`
if [[ -z "$docker_proxy_exist" ]]
then
    echo "installing docker nginx proxy, one moment ..."
    ssh $2 "docker run -d --restart=always -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name=proxy jwilder/nginx-proxy"
fi

# sync it
if [ "$3" == "" ]
then
    rsync -avzr $1 $2:~/sites/ && ssh $2 "cd ~/sites/$1 && docker-compose stop && docker-compose up && docker-compose logs"
else
    rsync -avzr $1 $2:~/sites/ && ssh $2 "cd ~/sites/$1 && docker-compose stop && docker-compose -f $3 up && docker-compose logs"
fi
